### ISSUE TITLE
Display results in tabular form?

### ISSUE THREAD

**Issue by bmitch** [beaorn/hrt#1]
Very cool project!

Was wondering if you'd be into something like this where the results would be displayed in tabular data?

```
+----------+-------------------------------------+
| Callsign | C4LLS1GN                            |
+----------+-------------------------------------+
| Name     | Nikola Tesla                        |
+----------+-------------------------------------+
| Location | Colorado Springs, CO, United States |
+----------+-------------------------------------+
| Classs   | E                                   |
+----------+-------------------------------------+
Source: QRZ
```

If interested I could attempt at a PR. Thanks.

**Comment by beaorn** [comment]
@bmitch I think the tabular output would be great. If you are interested and have time to put in a PR for that, that would be awesome, thanks!

**Comment by beaorn** [comment]
Implemented by https://github.com/beaorn/hrt/pull/3
